[tool.poetry]
name = "cdisc-crf-generator"
version = "0.1.0"
description = "Generate CRFs from CDISC Library"
authors = ["You <you@example.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { from = "src", include = "cdisc_library_client" },
    { from = "src", include = "crfgen" }
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
openapi-python-client = "^0.25"
jinja2 = "^3.1"
pydantic = "^2.7"
requests = "^2.32"
pandas = "^2.2"
openpyxl = "^3.1"
python-docx = "^1.1"
odmlib = {git = "https://github.com/swhume/odmlib.git", rev = "57b8ae069b1d6783cf73b8860b85dee6be0853ed"}
httpx = "^0.28.1"
python-dotenv = "^1.1.1"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
ruff = "^0.12.9"
pytest = "^8.0"
pytest-cov = "^6.2"
pre-commit = "^4.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
skip = ["src/cdisc_library_client"]
