name: CI
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: |
          chmod +x setup.sh
          ./setup.sh
      - name: Pre-commit checks
        run: poetry run pre-commit run --all-files --show-diff-on-failure
      - name: Build canonical JSON
        env:
          CDISC_PRIMARY_KEY: ${{ secrets.CDISC_PRIMARY_KEY }}
        run: poetry run scripts/build_canonical.py
      - name: Build all formats
        run: |
          poetry run scripts/build.py --source crf.json --outdir artefacts
      - name: Run tests
        run: poetry run pytest -q
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: artefacts
          path: artefacts
