name: CI
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '1.7.1'
      - name: Install dependencies
        run: poetry install -n
      - name: Build canonical JSON
        env:
          CDISC_PRIMARY_KEY: ${{ secrets.CDISC_PRIMARY_KEY }}
        run: poetry run scripts/build_canonical.py
      - name: Build all formats
        run: |
          poetry run scripts/build.py --source crf.json --outdir artefacts
      - name: Run tests
        run: poetry run pytest -q
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: artefacts
          path: artefacts
