name: Release Artefacts

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-dev

      - name: Generate CRF JSON
        env:
          CDISC_API_KEY: ${{ secrets.CDISC_API_KEY }}
        run: poetry run build-canonical -o crf.json

      - name: Build all formats
        run: poetry run build --outdir artefacts

      - name: Archive artefacts
        run: zip -r artefacts.zip artefacts/

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          asset_path: artefacts.zip
          asset_name: crf-artefacts-${{ github.ref_name }}.zip
          asset_content_type: application/zip
